fr.insee.rmes.magma.api.sparqlEndpoint=
#springdoc.swagger-ui.urls[0].url=/openapi-diffusion.yaml
#springdoc.swagger-ui.urls[0].name=API Diffusion
#springdoc.swagger-ui.urls[1].url=/openapi-gestion.yaml
#springdoc.swagger-ui.urls[1].name=API Gestion
fr.insee.rmes.magma.api.freemarker.locale-language=fr
properties.logger.prefix-for-properties=fr,debug, trace, info, logging, spring, server, management, springdoc, properties
spring.jackson.mapper.sort-properties-alphabetically=false
fr.insee.rmes.magma.api.geographie.types-autorises=Commune,CommuneAssociee,CommuneDeleguee,Canton,CantonOuVille,Arrondissement,ArrondissementMunicipal,Departement,Pays,Region,Intercommunalite,District,AireDAttractionDesVilles2020,BassinDeVie2022,CollectiviteDOutreMer,CirconscriptionTerritoriale,Iris,QuartierPrioritaireDeLaPolitiqueDeLaVille2024,ZoneDEmploi2020,UniteUrbaine2020