fr.insee.rmes.magma.api.sparqlEndpoint=
fr.insee.rmes.magma.api.freemarker.locale-language=fr
properties.logger.prefix-for-properties=fr,debug, trace, info, logging, spring, server, management, springdoc, properties
spring.jackson.mapper.sort-properties-alphabetically=false
fr.insee.rmes.magma.api.geographie.types-autorises=Commune,CommuneAssociee,CommuneDeleguee,Canton,CantonOuVille,Arrondissement,ArrondissementMunicipal,Departement,Pays,Region,Intercommunalite,District,AireDAttractionDesVilles2020,BassinDeVie2022,CollectiviteDOutreMer,CirconscriptionTerritoriale,Iris,QuartierPrioritaireDeLaPolitiqueDeLaVille2024,ZoneDEmploi2020,UniteUrbaine2020
fr.insee.rmes.role.administrateur=
fr.insee.rmes.role.gestionnaire.dataset=Gestionnaire_jeu_donnees_RMESGNCS
fr.insee.rmes.security.whitelist-matchers=
spring.security.oauth2.resourceserver.jwt.issuer-uri=
fr.insee.rmes.security.token.oidc-claim-role=realm_access
fr.insee.rmes.security.token.oidc-claim-username=preferred_username
fr.insee.rmes.security.token.oidc-roles-in-claim-role=roles
fr.insee.rmes.security.token.email=email