name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven
        run: mvn install --file pom.xml
      - name: Upload war
        uses: actions/upload-artifact@v4
        with:
          name: war-file
          path: target/*.war

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download war
        uses: actions/download-artifact@v4
        with:
          name: war-file
          path: target
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: List files in the repository
        run: ls -la
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile
          tags: inseefr/magma-back-office:latest

